### ISSUE TITLE
Remove the need to click on the "Add some content!" line before being able to leave notes in a new Document

### ISSUE THREAD

**Issue by N-G-X** [dantheuber/keepr#3]
When creating a new document, after creating the document and clicking `Edit`, the user must click on the _Add some content!_ line before being able to leave notes. This is pretty annoying, the user should be able to start editing/creating right away after going into edit mode without having to click on the `Edit` button. This may be entirely fixed by addressing issue #2

**Comment by dantheuber** [comment]
addressed this in PR #6
